### ISSUE TITLE
Net::IMAP::NoResponseError:  Invalid credentials (Failure)

### ISSUE THREAD

**Issue by richardsondx** [nfo/gmail_xoauth#11]
I did something very similar to the solution provided here:
http://stackoverflow.com/questions/9084701/how-to-implement-gmail-imap-with-omniauth

but I keep getting:
[2] pry(#<SessionsController>)> imap.authenticate('XOAUTH2', email, access_token)
Net::IMAP::NoResponseError:  Invalid credentials (Failure)
from /Users/Richardson/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/imap.rb:1171:in `get_tagged_response'

Maybe, the token provided by Omniauth might not be correct.
---
Ruby 2.2.0

Gems:
Using oauth2 1.0.0
Using omniauth 1.2.2
Using omniauth-oauth2 1.3.1
Using gmail_xoauth 0.4.1

**Comment by richardsondx** [comment]
Fixed: Using the correct scope matters

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_CLIENT_SECRET'], 
  {
  	scope: ['https://mail.google.com/', 'https://www.googleapis.com/auth/userinfo.email']
  }

end

**Comment by chriskacerguis** [comment]
Looks like this is fixed.
